version: "3"
services:
  client:
    build:
      context: ./task-management-app-client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./task-management-app-server
    ports:
      - "8000:8000"
